version: "3"

services:
  minecraft:
    image: itzg/minecraft-bedrock-server
    ports:
      - "19132:19132"
    volumes:
      - "mc:/data"
    environment:
      EULA: "TRUE"
      GAMEMODE: survival
      DIFFICULTY: hard

    restart: always

volumes:
  mc: {}
